# Generated by Django 3.1.1 on 2020-09-28 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('ready', 'Ready'), ('delivered', 'Delivered')], default=('canceled', 'Canceled'), max_length=15)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('canceled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canceled_by', to=settings.AUTH_USER_MODEL)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cid', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_by', to=settings.AUTH_USER_MODEL)),
                ('ready_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_by', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
