# Generated by Django 3.1.1 on 2020-09-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownersapp', '0002_delete_ownerprofile'),
        ('bookingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(to='ownersapp.Services'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('ready', 'Ready'), ('delivered', 'Delivered')], default=('pending', 'Pending'), max_length=15),
        ),
    ]
