# Generated by Django 3.1.1 on 2020-09-28 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0002_auto_20200928_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='brand',
            field=models.CharField(choices=[('aprila', 'Aprila'), ('bajaj', 'Bajaj'), ('harley-davidson', 'Harley-Davidson'), ('hero', 'Hero'), ('honda', 'Honda'), ('ktm', 'KTM'), ('mahindra', 'Mahindra'), ('royal enfield', 'Royal Enfield'), ('suzuki', 'Suzuki'), ('tvs', 'TVS'), ('vespa', 'Vespa'), ('yamaha', 'Yamaha')], default=('aprila', 'Aprila'), max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
