# Generated by Django 3.1.1 on 2020-09-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0003_auto_20200928_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='brand',
            field=models.CharField(choices=[('aprila', 'Aprila'), ('bajaj', 'Bajaj'), ('harley-davidson', 'Harley-Davidson'), ('hero', 'Hero'), ('honda', 'Honda'), ('ktm', 'KTM'), ('mahindra', 'Mahindra'), ('royal enfield', 'Royal Enfield'), ('suzuki', 'Suzuki'), ('tvs', 'TVS'), ('vespa', 'Vespa'), ('yamaha', 'Yamaha')], max_length=30),
        ),
    ]
