# Generated by Django 3.1.1 on 2020-09-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0008_auto_20200930_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
