# Generated by Django 3.1.1 on 2020-09-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownersapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerProfile',
        ),
    ]
