# Generated by Django 3.1.1 on 2020-09-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsapp', '0003_auto_20200928_2231'),
        ('ownersapp', '0002_delete_ownerprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
